#!/usr/bin/env python3
"""Wrap shadercross output blobs into committed C++ byte-array headers.

Reads, for each shader stem (e.g. "blit.vert"), the three SDL_shadercross outputs
in <input-dir>:

    <stem>.spv   (SPIR-V    — Vulkan)
    <stem>.dxil  (DXIL      — Direct3D 12)
    <stem>.msl   (MSL text  — Metal)

and emits <output-dir>/<stem_with_underscores>.h exposing each as an `inline
constexpr unsigned char[]` plus the per-format entrypoint name. The engine selects
the right variant at runtime from SDL_GetGPUShaderFormats (see shader_format.h).

These headers are the build's source of truth — CI and the shipped binary consume
them and never invoke a shader compiler. Regeneration is a dev-only step run on a
runner that has the toolchain (see .github/workflows/regenerate-shaders.yml).

Usage: wrap_headers.py <input-dir> <output-dir> [stem ...]
       (default stems: blit.vert blit.frag)
"""

import re
import sys
from pathlib import Path

DEFAULT_STEMS = ["blit.vert", "blit.frag"]

# SPIR-V and DXIL keep the source entrypoint; SPIRV-Cross renames "main" (reserved
# in MSL) on the Metal path. We detect the renamed MSL entry from its stage-qualified
# function declaration, falling back to the SPIRV-Cross default.
_MSL_ENTRY = re.compile(r"\b(?:vertex|fragment|kernel)\b[^\n;{]*?\b(\w+)\s*\(")


def msl_entrypoint(msl_text: str) -> str:
    match = _MSL_ENTRY.search(msl_text)
    return match.group(1) if match else "main0"


def byte_array(name: str, data: bytes) -> str:
    rows = []
    for i in range(0, len(data), 12):
        rows.append("    " + " ".join(f"0x{b:02x}," for b in data[i:i + 12]))
    body = "\n".join(rows)
    return (f"inline constexpr unsigned char {name}[] = {{\n{body}\n}};")


def emit(stem: str, input_dir: Path, output_dir: Path) -> None:
    ns = stem.replace(".", "_")
    spirv = (input_dir / f"{stem}.spv").read_bytes()
    dxil = (input_dir / f"{stem}.dxil").read_bytes()
    msl_text = (input_dir / f"{stem}.msl").read_bytes()
    msl_entry = msl_entrypoint(msl_text.decode("utf-8", "replace"))
    # SPIR-V and DXIL are binary; MSL is consumed by Metal as a source string, so it is
    # NUL-terminated (its byte length, including the terminator, is the variant size).
    msl_bytes = msl_text + b"\x00"

    header = output_dir / f"{ns}.h"
    with header.open("w", encoding="utf-8", newline="\n") as out:
        out.write(
            "#pragma once\n"
            "// AUTO-GENERATED by shaders/wrap_headers.py (SDL_shadercross output).\n"
            "// DO NOT EDIT — regenerate via .github/workflows/regenerate-shaders.yml.\n"
            f"// Source: shaders/src/{stem}.hlsl\n\n"
            f"namespace gbcpp::shaders::{ns} {{\n\n"
        )
        out.write(byte_array("kSpirv", spirv) + "\n\n")
        out.write(byte_array("kDxil", dxil) + "\n\n")
        out.write(byte_array("kMsl", msl_bytes) + "\n\n")
        out.write('inline constexpr const char* kSpirvEntrypoint = "main";\n')
        out.write('inline constexpr const char* kDxilEntrypoint  = "main";\n')
        out.write(f'inline constexpr const char* kMslEntrypoint   = "{msl_entry}";\n\n')
        out.write(f"}}  // namespace gbcpp::shaders::{ns}\n")
    print(f"wrote {header} "
          f"(spirv {len(spirv)} B, dxil {len(dxil)} B, msl {len(msl_bytes)} B, "
          f"msl entry '{msl_entry}')")


def main(argv: list[str]) -> int:
    if len(argv) < 3:
        print(__doc__)
        return 2
    input_dir = Path(argv[1])
    output_dir = Path(argv[2])
    stems = argv[3:] or DEFAULT_STEMS
    output_dir.mkdir(parents=True, exist_ok=True)
    for stem in stems:
        emit(stem, input_dir, output_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
