#include "deck.h"

#include <algorithm>
#include <array>
#include <stdexcept>
#include <string>
#include <string_view>

#include "retropp/image.h"  // loadMapPng / IndexGrid — the deck sections' authoring format

namespace vant {

using namespace retropp;

namespace {

// ── The deck sections are MAP PNGS: 20×18 16-bit grayscale images, one pixel per 16px cell,
// authored/regenerated by gen_vantium_assets.py and hand-editable in any image editor (each cell
// class is a distinct grey band — ids spread evenly across the 16-bit range, class × 3855; see
// MapGlyph in layout.h). loadMapPng decodes each to an IndexGrid; every call is a literal path
// under the Embed default, so the maps bake into the binary like every other Vantium asset.
// The vocabulary rules the maps are authored against (validated below at decode):
//   • every PodTop pairs with a PodBot directly beneath it;
//   • rolled-only corridors are exactly one cell tall between structure bands;
//   • RotorAnchor/VentAnchor own their 4×4 / 2×2 fill cells.

const std::array<const IndexGrid*, 9>& sectionGrids() {
    // Loaded once, on the first build — one loadMapPng statement per section so the build scan
    // keys each literal path cleanly.
    static const IndexGrid bow   = loadMapPng("examples/vantium/assets/vantium_deck_bow.png");
    static const IndexGrid stern = loadMapPng("examples/vantium/assets/vantium_deck_stern.png");
    static const IndexGrid strip = loadMapPng("examples/vantium/assets/vantium_deck_strip.png");
    static const IndexGrid mid1  = loadMapPng("examples/vantium/assets/vantium_deck_mid1.png");
    static const IndexGrid mid2  = loadMapPng("examples/vantium/assets/vantium_deck_mid2.png");
    static const IndexGrid mid3  = loadMapPng("examples/vantium/assets/vantium_deck_mid3.png");
    static const IndexGrid mid4  = loadMapPng("examples/vantium/assets/vantium_deck_mid4.png");
    static const IndexGrid mid5  = loadMapPng("examples/vantium/assets/vantium_deck_mid5.png");
    static const IndexGrid mid6  = loadMapPng("examples/vantium/assets/vantium_deck_mid6.png");
    static const std::array<const IndexGrid*, 9> grids{&bow, &mid1, &mid2, &mid3, &mid4, &mid5,
                                                       &mid6, &strip, &stern};
    return grids;
}
// sectionGrids() index layout: [0] bow, [1..6] the six mids, [7] strip, [8] stern.
constexpr int kGridBow = 0, kGridMidBase = 1, kGridStrip = 7, kGridStern = 8;

MapGlyph decodeId(std::uint16_t id) {
    if (id == 0) return MapGlyph::Void;  // pure black — the hull holes
    const int off = id - kMapFirstId;
    if (off < 0 || off % kMapIdStep != 0 || 1 + off / kMapIdStep >= kMapGlyphCount) {
        throw std::logic_error("vantium deck: map id " + std::to_string(id) +
                               " is not on the class ladder (16383 + k*3072)");
    }
    return static_cast<MapGlyph>(1 + off / kMapIdStep);
}

// The starfield map: 12×8 cells of two star variants + void, tiled by Repeat wrap.
constexpr std::array<std::string_view, 8> kStarMap{
    "A..B...A..B.",
    "....A....B..",
    ".B....A.....",
    "...A....B..A",
    "A....B......",
    "..B....A.B..",
    ".....A......",
    "B...B....A..",
};

std::uint32_t nextRand(std::uint32_t& s) { s = s * 1664525u + 1013904223u; return s; }

}  // namespace

void Deck::stampCell16(int c, int r, TileArt art, TilePal pal, bool flipX, bool flipY, bool rot90,
                       const VantAssets& assets) {
    const std::uint16_t base = assets.artTile(art);
    const int tx = c * 2;
    const int ty = r * 2;
    const int stride = kWorldW / kTile;  // 320 engine tiles per deck row
    for (int dy = 0; dy < 2; ++dy) {
        for (int dx = 0; dx < 2; ++dx) {
            // Orienting a 2×2 GROUP means two things at once: pick the mirrored/rotated SOURCE
            // sub-tile, and mirror/rotate that tile's own pixels — flips + Rotation compose here.
            int      sx = dx, sy = dy;
            Rotation rot = Rotation::None;
            if (rot90) {
                sx  = dy;
                sy  = 1 - dx;
                rot = Rotation::Rot90;
            } else {
                if (flipX) sx = 1 - dx;
                if (flipY) sy = 1 - dy;
            }
            TileCell& cell = tiles_[static_cast<std::size_t>(ty + dy) * stride + tx + dx];
            cell.tile     = static_cast<std::uint16_t>(base + sx + kTileStride8 * sy);
            cell.atlas    = assets.tileAtlas();
            cell.palette  = assets.tilePals[pal];
            cell.flipX    = flipX;
            cell.flipY    = flipY;
            cell.rotation = rot;
        }
    }
}

void Deck::build(int shipNum, const VantAssets& assets) {
    const int stride = kWorldW / kTile;
    tiles_.assign(static_cast<std::size_t>(stride) * (kDeckRows * 2), TileCell{});
    solid_.assign(static_cast<std::size_t>(kDeckRows) * kDeckCols, 0);
    podIndex_.assign(static_cast<std::size_t>(kDeckRows) * kDeckCols, -1);
    pods_.clear();
    mineSpawns_.clear();

    const auto& grids = sectionGrids();

    // Ship N's section line-up: bow, five seeded mids, the strip, the stern. Deterministic per
    // ship — dreadnought N is always the same hull, so its canyons are learnable.
    std::array<const IndexGrid*, kSections> lineup{};
    lineup[0] = grids[kGridBow];
    std::uint32_t seed = static_cast<std::uint32_t>(shipNum) * 2654435761u + 97u;
    for (int m = 0; m < kMidSlots; ++m) {
        lineup[static_cast<std::size_t>(1 + m)] = grids[kGridMidBase + nextRand(seed) % 6u];
    }
    lineup[6] = grids[kGridStrip];
    lineup[7] = grids[kGridStern];

    // Decode the whole deck's glyphs up front (validating ids + section shape), so the stamping
    // switch and the shadow pass both read one uniform grid.
    std::vector<MapGlyph> glyphs(static_cast<std::size_t>(kDeckRows) * kDeckCols, MapGlyph::Void);
    for (int s = 0; s < kSections; ++s) {
        const IndexGrid& g = *lineup[static_cast<std::size_t>(s)];
        if (g.width != kSectionCols || g.height != kDeckRows) {
            throw std::logic_error("vantium deck: section map is " + std::to_string(g.width) +
                                   "x" + std::to_string(g.height) + ", want 20x18");
        }
        for (int r = 0; r < kDeckRows; ++r) {
            for (int lc = 0; lc < kSectionCols; ++lc) {
                glyphs[static_cast<std::size_t>(r) * kDeckCols + s * kSectionCols + lc] =
                    decodeId(g.at(lc, r));
            }
        }
    }
    auto glyphAt = [&](int c, int r) { return glyphs[static_cast<std::size_t>(r) * kDeckCols + c]; };

    // Default every engine tile to the empty (fully transparent) art so hull holes show stars.
    for (int r = 0; r < kDeckRows; ++r) {
        for (int c = 0; c < kDeckCols; ++c) stampCell16(c, r, T_EMPTY, TP_DECK, false, false, false, assets);
    }

    int stripC0 = kDeckCols, stripC1 = -1, stripR = 0;
    for (int r = 0; r < kDeckRows; ++r) {
        for (int c = 0; c < kDeckCols; ++c) {
            const std::size_t si = static_cast<std::size_t>(r) * kDeckCols + c;
            switch (glyphAt(c, r)) {
                case MapGlyph::Void: break;  // stays the empty stamp
                case MapGlyph::PlateA: stampCell16(c, r, T_PLATE_A, TP_DECK, false, false, false, assets); break;
                case MapGlyph::PlateB: stampCell16(c, r, T_PLATE_B, TP_DECK, false, false, false, assets); break;
                case MapGlyph::PlateC: stampCell16(c, r, T_PLATE_C, TP_DECK, false, false, false, assets); break;
                case MapGlyph::HazardH:
                    stampCell16(c, r, T_HAZARD, TP_HAZARD, false, r >= kDeckRows / 2, false, assets);
                    break;
                case MapGlyph::HazardV: stampCell16(c, r, T_HAZARD, TP_HAZARD, false, false, true, assets); break;
                case MapGlyph::Corner:
                    stampCell16(c, r, T_CORNER, TP_HAZARD, (c % kSectionCols) >= kSectionCols / 2,
                                r >= kDeckRows / 2, false, assets);
                    break;
                case MapGlyph::Struct:
                    stampCell16(c, r, T_STRUCT, TP_STRUCT, false, false, false, assets);
                    solid_[si] = 1;
                    break;
                case MapGlyph::PipeH: stampCell16(c, r, T_PIPE, TP_DECK, false, false, false, assets); break;
                case MapGlyph::PipeV: stampCell16(c, r, T_PIPE, TP_DECK, false, false, true, assets); break;
                case MapGlyph::MineSpawn:
                    stampCell16(c, r, T_PLATE_A, TP_DECK, false, false, false, assets);
                    mineSpawns_.push_back(VCell{c, r});
                    break;
                case MapGlyph::Chevron:
                    stampCell16(c, r, T_CHEVRON, TP_STRIP, false, false, false, assets);
                    stripC0 = std::min(stripC0, c);
                    stripC1 = std::max(stripC1, c);
                    stripR  = std::min(stripR == 0 ? r : stripR, r);
                    break;
                case MapGlyph::PodTop: {
                    if (r + 1 >= kDeckRows || glyphAt(c, r + 1) != MapGlyph::PodBot) {
                        throw std::logic_error("vantium deck: pod top without a bottom below");
                    }
                    stampCell16(c, r, T_POD_TOP, TP_POD_A, false, false, false, assets);
                    stampCell16(c, r + 1, T_POD_BOT, TP_POD_A, false, false, false, assets);
                    const auto pi = static_cast<std::int16_t>(pods_.size());
                    pods_.push_back(Pod{VCell{c, r}, true});
                    podIndex_[si] = pi;
                    podIndex_[si + kDeckCols] = pi;
                    break;
                }
                case MapGlyph::PodBot: break;  // handled by its top
                case MapGlyph::RotorAnchor:
                    for (int dy = 0; dy < 4; ++dy) {
                        for (int dx = 0; dx < 4; ++dx) {
                            stampCell16(c + dx, r + dy, static_cast<TileArt>(T_ROTOR0 + dy * 4 + dx),
                                        TP_ROTOR, false, false, false, assets);
                            solid_[static_cast<std::size_t>(r + dy) * kDeckCols + c + dx] = 1;
                        }
                    }
                    break;
                case MapGlyph::RotorFill: break;  // covered by its anchor
                case MapGlyph::VentAnchor:
                    for (int dy = 0; dy < 2; ++dy) {
                        for (int dx = 0; dx < 2; ++dx) {
                            stampCell16(c + dx, r + dy, static_cast<TileArt>(T_VENT0 + dy * 2 + dx),
                                        TP_VENT, false, false, false, assets);
                            solid_[static_cast<std::size_t>(r + dy) * kDeckCols + c + dx] = 1;
                        }
                    }
                    break;
                case MapGlyph::VentFill: break;  // covered by its anchor
            }
        }
    }

    // The shadow pass: a plain plate directly beneath raised structure restamps under the darker
    // ramp — the whole deck gains depth from one palette swap, no shadow art.
    for (int r = 1; r < kDeckRows; ++r) {
        for (int c = 0; c < kDeckCols; ++c) {
            const MapGlyph g = glyphAt(c, r);
            if ((g == MapGlyph::PlateA || g == MapGlyph::PlateB || g == MapGlyph::PlateC) &&
                solid_[static_cast<std::size_t>(r - 1) * kDeckCols + c]) {
                const TileArt art = g == MapGlyph::PlateA ? T_PLATE_A
                                                          : (g == MapGlyph::PlateB ? T_PLATE_B : T_PLATE_C);
                stampCell16(c, r, art, TP_DECK_SHADOW, false, false, false, assets);
            }
        }
    }

    stripX0_ = deckPxX(stripC0);
    stripX1_ = deckPxX(stripC1 + 1);
    stripY_  = deckPxY(stripR);

    // The starfield (built fresh per ship — cheap, and keeps ownership in one place).
    starTiles_.assign(static_cast<std::size_t>(kStarCols8) * kStarRows8, TileCell{});
    starSlots_.clear();
    for (int r = 0; r < kStarRows8 / 2; ++r) {
        for (int c = 0; c < kStarCols8 / 2; ++c) {
            const char ch  = kStarMap[static_cast<std::size_t>(r)][static_cast<std::size_t>(c)];
            const TileArt art = ch == 'A' ? T_STAR_A : (ch == 'B' ? T_STAR_B : T_EMPTY);
            const std::uint16_t base = assets.artTile(art);
            for (int dy = 0; dy < 2; ++dy) {
                for (int dx = 0; dx < 2; ++dx) {
                    const std::size_t slot = static_cast<std::size_t>(r * 2 + dy) * kStarCols8 + c * 2 + dx;
                    TileCell& cell = starTiles_[slot];
                    cell.tile    = static_cast<std::uint16_t>(base + dx + kTileStride8 * dy);
                    cell.atlas   = assets.tileAtlas();
                    cell.palette = assets.tilePals[TP_STAR_A];
                    if (ch != '.') starSlots_.push_back(slot);
                }
            }
        }
    }
}

void Deck::setStarPalette(PaletteId pal) {
    for (const std::size_t slot : starSlots_) starTiles_[slot].palette = pal;
}

void Deck::setPodPalette(PaletteId pal) {
    // Computed on the fly per alive pod (8 engine tiles each), so scorching in any order needs no
    // slot bookkeeping — a dead pod simply stops being visited.
    const int stride = kWorldW / kTile;
    for (const Pod& pod : pods_) {
        if (!pod.alive) continue;
        for (int rr = pod.cell.r; rr <= pod.cell.r + 1; ++rr) {
            for (int dy = 0; dy < 2; ++dy) {
                for (int dx = 0; dx < 2; ++dx) {
                    tiles_[static_cast<std::size_t>(rr * 2 + dy) * stride + pod.cell.c * 2 + dx]
                        .palette = pal;
                }
            }
        }
    }
}

bool Deck::rectHitsSolid(float x, float y, float w, float h) const {
    if (y >= static_cast<float>(kDeckBottom) || y + h <= static_cast<float>(kDeckTop)) return false;
    const int c0 = std::max(0, static_cast<int>(x) / kCell);
    const int c1 = std::min(kDeckCols - 1, static_cast<int>(x + w - 0.01f) / kCell);
    const int r0 = std::max(0, (static_cast<int>(y) - kDeckTop) / kCell);
    const int r1 = std::min(kDeckRows - 1, (static_cast<int>(y + h - 0.01f) - kDeckTop) / kCell);
    for (int r = r0; r <= r1; ++r) {
        for (int c = c0; c <= c1; ++c) {
            if (solid_[static_cast<std::size_t>(r) * kDeckCols + c]) return true;
        }
    }
    return false;
}

int Deck::podAt(float x, float y) const {
    if (y < static_cast<float>(kDeckTop) || y >= static_cast<float>(kDeckBottom)) return -1;
    const int c = static_cast<int>(x) / kCell;
    const int r = (static_cast<int>(y) - kDeckTop) / kCell;
    if (c < 0 || c >= kDeckCols || r < 0 || r >= kDeckRows) return -1;
    const std::int16_t pi = podIndex_[static_cast<std::size_t>(r) * kDeckCols + c];
    if (pi < 0 || !pods_[static_cast<std::size_t>(pi)].alive) return -1;
    return pi;
}

void Deck::scorchPod(int i, const VantAssets& assets) {
    Pod& pod = pods_[static_cast<std::size_t>(i)];
    if (!pod.alive) return;
    pod.alive = false;
    stampCell16(pod.cell.c, pod.cell.r, T_POD_TOP_X, TP_POD_A, false, false, false, assets);
    stampCell16(pod.cell.c, pod.cell.r + 1, T_POD_BOT_X, TP_POD_A, false, false, false, assets);
}

}  // namespace vant
